### PR TITLE
fixes, opuscapita/email#20

### PR DESCRIPTION
**Pull request by sureshvarman-cronj**

### CODE REVIEW

**Comment by kwierchris** [comment]
user/x-tenant-user-mgmt is a very mighty role. Why does the service need this permission?

**Comment by sureshvarman-cronj** [comment]
Because, we need to fetch the user details to get the tenant information.

**Comment by kwierchris** [comment]
I just added a resource group **x-tenant-user-read** to the user service acl. This still provides a lot access but at least it could not change or create user. So please adjust this PR.

**Comment by sureshvarman-cronj** [comment]
Sure

**Pull request merged**
