### PR TITLE
Customer/supplier manage permission for routing service

### PR DESCRIPTION
**Pull request by StefanDywersant**
Routing service is going to have external routes import feature. Auto-creation (if customer/supplier does not exists) is a part of this feature, so supplier/customer manage permissions are needed.

### CODE REVIEW

**Comment by StefanDywersant** [comment]
Should I create new resourceId inside customer/supplier which will grant only create operation?
Currently x-tenant-manage is the only resourceId which grants creating suppliers/customers.

**Comment by denic** [comment]
@StefanDywersant Is this still needed?

**Comment by StefanDywersant** [comment]
I'll verify that and either update the PR or close.

**Comment by StefanDywersant** [comment]
This PR is not valid anymore. Moreover, the change has been done in some other PR.

**Pull request closed without merging**
